version: '2.3'
networks:
  back-end:

services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
      - 5005:5005
    networks:
      - back-end

  app_1:
    build:
      context: .
      dockerfile: Dockerfile-app1
    image: app1:v1
    container_name: app_1
    expose:
      - "5000"
    networks:
      - back-end

  app_2:
    build:
      context: .
      dockerfile: Dockerfile-app2
    image: app2:v1
    container_name: app_2
    expose:
      - "5000"
    networks:
      - back-end
